# Generated by Django 5.0.6 on 2024-06-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_essayoriginaltext_originalessaytext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='grade',
        ),
    ]
